# Generated by Django 6.0.2 on 2026-03-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('centro', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tecnicos',
            },
        ),
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id_casette', models.AutoField(primary_key=True, serialize=False)),
                ('cassette', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('qr_casette', models.CharField(max_length=255)),
                ('organo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('tecnico', models.ForeignKey(db_column='tecnicoIdTecnico', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cassettes',
            },
        ),
        migrations.CreateModel(
            name='Citologia',
            fields=[
                ('id_citologia', models.AutoField(primary_key=True, serialize=False)),
                ('citologia', models.CharField(max_length=50)),
                ('tipo_citologia', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('qr_citologia', models.CharField(max_length=255)),
                ('organo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('tecnico', models.ForeignKey(db_column='tecnicoIdTecnico', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'citologias',
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tincion', models.CharField(max_length=255)),
                ('qr_muestra', models.CharField(max_length=255)),
                ('cassette', models.ForeignKey(db_column='cassetteIdCassette', on_delete=django.db.models.deletion.CASCADE, to='api.cassette')),
            ],
            options={
                'db_table': 'muestras',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('muestra', models.ForeignKey(db_column='muestraIdMuestra', on_delete=django.db.models.deletion.CASCADE, to='api.muestra')),
            ],
            options={
                'db_table': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='MuestraCitologia',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tincion', models.CharField(max_length=255)),
                ('qr_muestra', models.CharField(max_length=255)),
                ('citologia', models.ForeignKey(db_column='citologiaIdCitologia', on_delete=django.db.models.deletion.CASCADE, to='api.citologia')),
            ],
            options={
                'db_table': 'muestrascitologia',
            },
        ),
        migrations.CreateModel(
            name='ImagenCitologia',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_citologia/')),
                ('muestra', models.ForeignKey(db_column='muestraIdMuestra', on_delete=django.db.models.deletion.CASCADE, to='api.muestracitologia')),
            ],
            options={
                'db_table': 'imagenescitologia',
            },
        ),
    ]
