# Generated by Django 6.0.3 on 2026-03-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='informe_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='informe_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='informe_imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='informe_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='informe_tincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='patologo_responsable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_tincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='patologo_responsable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='qr_casette',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='qr_citologia',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
