# Generated by Django 6.0.3 on 2026-03-04 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cassette_descripcion_microscopica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraTubo',
            fields=[
                ('id_muestra', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tincion', models.CharField(max_length=255)),
                ('qr_muestra', models.CharField(max_length=255)),
                ('qr_imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'muestrastubo',
            },
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='descripcion_microscopica',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='diagnostico_final',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='informe_descripcion',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='informe_fecha',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='informe_imagen',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='informe_observaciones',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='informe_tincion',
        ),
        migrations.RemoveField(
            model_name='citologia',
            name='patologo_responsable',
        ),
        migrations.AddField(
            model_name='cassette',
            name='informacion_clinica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='qr_imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='muestracitologia',
            name='qr_imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='informe_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='patologo_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='id_citologia',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='tecnico',
            field=models.ForeignKey(blank=True, db_column='tecnico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.muestra'),
        ),
        migrations.AlterField(
            model_name='imagencitologia',
            name='id_imagen',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagencitologia',
            name='muestra',
            field=models.ForeignKey(db_column='muestra_id', on_delete=django.db.models.deletion.CASCADE, to='api.muestracitologia'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cassette'),
        ),
        migrations.AlterField(
            model_name='muestracitologia',
            name='citologia',
            field=models.ForeignKey(db_column='citologia_id', on_delete=django.db.models.deletion.CASCADE, to='api.citologia'),
        ),
        migrations.AlterField(
            model_name='muestracitologia',
            name='id_muestra',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='apellidos',
            field=models.CharField(db_column='last_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_tecnico',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombre',
            field=models.CharField(db_column='first_name', max_length=255),
        ),
        migrations.CreateModel(
            name='ImagenTubo',
            fields=[
                ('id_imagen', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_tubo/')),
                ('muestra', models.ForeignKey(db_column='muestra_id', on_delete=django.db.models.deletion.CASCADE, to='api.muestratubo')),
            ],
            options={
                'db_table': 'imagenestubo',
            },
        ),
        migrations.CreateModel(
            name='Tubo',
            fields=[
                ('id_tubo', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tubo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('informacion_clinica', models.TextField(blank=True, null=True)),
                ('descripcion_microscopica', models.TextField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('patologo_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_tubo', models.CharField(max_length=255, unique=True)),
                ('organo', models.CharField(max_length=255)),
                ('informe_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('informe_fecha', models.DateField(blank=True, null=True)),
                ('informe_tincion', models.CharField(blank=True, max_length=255, null=True)),
                ('informe_observaciones', models.TextField(blank=True, null=True)),
                ('informe_imagen', models.BinaryField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(blank=True, db_column='tecnico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tubos',
            },
        ),
        migrations.AddField(
            model_name='muestratubo',
            name='tubo',
            field=models.ForeignKey(db_column='tubo_id', on_delete=django.db.models.deletion.CASCADE, to='api.tubo'),
        ),
    ]
