# Generated by Django 6.0.3 on 2026-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hematologia_muestrahematologia_imagenhematologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagentubo',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
