# Generated by Django 6.0.3 on 2026-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_imagentubo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrahematologia',
            name='informe_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestrahematologia',
            name='informe_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestrahematologia',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='informes_hematologia/'),
        ),
        migrations.AddField(
            model_name='muestrahematologia',
            name='informe_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestrahematologia',
            name='informe_tincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
