# Generated by Django 6.0.3 on 2026-03-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_imagentubo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microbiologia',
            fields=[
                ('id_microbiologia', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('microbiologia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('informacion_clinica', models.TextField(blank=True, null=True)),
                ('descripcion_microscopica', models.TextField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('patologo_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_microbiologia', models.CharField(max_length=255, unique=True)),
                ('organo', models.CharField(max_length=255)),
                ('informe_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('informe_fecha', models.DateField(blank=True, null=True)),
                ('informe_tincion', models.CharField(blank=True, max_length=255, null=True)),
                ('informe_observaciones', models.TextField(blank=True, null=True)),
                ('informe_imagen', models.BinaryField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(blank=True, db_column='tecnico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'microbiologias',
            },
        ),
        migrations.CreateModel(
            name='MuestraMicrobiologia',
            fields=[
                ('id_muestra', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tincion', models.CharField(max_length=255)),
                ('qr_muestra', models.CharField(max_length=255)),
                ('qr_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('microbiologia', models.ForeignKey(db_column='microbiologia_id', on_delete=django.db.models.deletion.CASCADE, to='api.microbiologia')),
            ],
            options={
                'db_table': 'muestrasmicrobiologia',
            },
        ),
        migrations.CreateModel(
            name='ImagenMicrobiologia',
            fields=[
                ('id_imagen', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_microbiologia/')),
                ('muestra', models.ForeignKey(db_column='muestra_id', on_delete=django.db.models.deletion.CASCADE, to='api.muestramicrobiologia')),
            ],
            options={
                'db_table': 'imagenesmicrobiologia',
            },
        ),
    ]
