# Generated by Django 6.0.3 on 2026-03-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_microbiologia_muestramicrobiologia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeResultado',
            fields=[
                ('id_informe', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tincion', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hematologia', models.ForeignKey(blank=True, db_column='hematologia_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hematologia')),
                ('microbiologia', models.ForeignKey(blank=True, db_column='microbiologia_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.microbiologia')),
                ('tubo', models.ForeignKey(blank=True, db_column='tubo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tubo')),
            ],
            options={
                'db_table': 'informesresultado',
            },
        ),
    ]
