# Generated by Django 6.0.3 on 2026-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_informe_to_muestrahematologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenhematologia',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestrahematologia',
            name='informe_imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
