# Generated by Django 6.0.3 on 2026-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_binary_images_hematologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestrahematologia',
            name='informe_descripcion',
        ),
        migrations.RemoveField(
            model_name='muestrahematologia',
            name='informe_fecha',
        ),
        migrations.RemoveField(
            model_name='muestrahematologia',
            name='informe_imagen',
        ),
        migrations.RemoveField(
            model_name='muestrahematologia',
            name='informe_observaciones',
        ),
        migrations.RemoveField(
            model_name='muestrahematologia',
            name='informe_tincion',
        ),
    ]
