# Generated by Django 6.0.3 on 2026-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0008_remove_redundant_informe_fields_hematologia_0007_informeresultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagencitologia',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenmicrobiologia',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
