# Generated by Django 6.0.3 on 2026-03-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_informeresultado_cassette_citologia'),
        ('api', '0010_alter_imagen_imagen_alter_imagencitologia_imagen_and_more'),
    ]

    operations = [
    ]
