# Generated by Django 6.0.3 on 2026-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_tecnico_to_cassette'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='volante_peticion',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='volante_peticion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cassette',
            name='volante_peticion_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='volante_peticion',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='volante_peticion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='volante_peticion_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hematologia',
            name='volante_peticion',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hematologia',
            name='volante_peticion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hematologia',
            name='volante_peticion_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='microbiologia',
            name='volante_peticion',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbiologia',
            name='volante_peticion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microbiologia',
            name='volante_peticion_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tubo',
            name='volante_peticion',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubo',
            name='volante_peticion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tubo',
            name='volante_peticion_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
