# Generated by Django 6.0.3 on 2026-03-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cassette_volante_peticion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraNecropsia',
            fields=[
                ('id_muestra', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tincion', models.CharField(max_length=255)),
                ('qr_muestra', models.CharField(max_length=255)),
                ('qr_imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'muestrasnecropsia',
            },
        ),
        migrations.CreateModel(
            name='ImagenNecropsia',
            fields=[
                ('id_imagen', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('imagen', models.BinaryField(blank=True, editable=True, null=True)),
                ('muestra', models.ForeignKey(db_column='muestra_id', on_delete=django.db.models.deletion.CASCADE, to='api.muestranecropsia')),
            ],
            options={
                'db_table': 'imagenesnecropsia',
            },
        ),
        migrations.CreateModel(
            name='Necropsia',
            fields=[
                ('id_necropsia', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('necropsia', models.CharField(max_length=50)),
                ('tipo_necropsia', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('qr_necropsia', models.CharField(max_length=255, unique=True)),
                ('qr_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('organo', models.CharField(max_length=255)),
                ('volante_peticion', models.BinaryField(blank=True, null=True)),
                ('volante_peticion_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('volante_peticion_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnico', models.ForeignKey(blank=True, db_column='tecnico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'necropsias',
            },
        ),
        migrations.AddField(
            model_name='muestranecropsia',
            name='necropsia',
            field=models.ForeignKey(db_column='necropsia_id', on_delete=django.db.models.deletion.CASCADE, to='api.necropsia'),
        ),
        migrations.AddField(
            model_name='informeresultado',
            name='necropsia',
            field=models.ForeignKey(blank=True, db_column='necropsia_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.necropsia'),
        ),
    ]
