# Generated by Django 6.0.3 on 2026-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_muestranecropsia_imagennecropsia_necropsia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='necropsia',
            name='datos_muerte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='examen_externo_cadaver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='fenomenos_cadavericos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
