# Generated by Django 6.0.3 on 2026-03-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_necropsia_datos_muerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestranecropsia',
            name='datos_relevantes_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestranecropsia',
            name='examen_interno_cadaver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestranecropsia',
            name='tecnica_apertura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
