# Generated by Django 6.0.2 on 2026-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_muestranecropsia_datos_relevantes_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenhematologia',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagentubo',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
