# Generated by Django 6.0.3 on 2026-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_imagenhematologia_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('organo', 'Organo'), ('tincion', 'Tincion'), ('tipo_citologia', 'Tipo citologia'), ('tipo_autopsia', 'Tipo autopsia'), ('analisis_informe', 'Analisis informe')], max_length=40)),
                ('valor', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_opciones',
                'ordering': ['tipo', 'orden', 'valor'],
                'unique_together': {('tipo', 'valor')},
            },
        ),
    ]
