# Generated by Django 6.0.3 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_imagenhematologia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='informe_imagen',
            field=models.FileField(blank=True, null=True, upload_to='informes_legacy/'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
        migrations.AlterField(
            model_name='hematologia',
            name='informe_imagen',
            field=models.FileField(blank=True, null=True, upload_to='informes_legacy/'),
        ),
        migrations.AlterField(
            model_name='hematologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagencitologia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenhematologia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenmicrobiologia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagennecropsia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagentubo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='informeresultado',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='informes/'),
        ),
        migrations.AlterField(
            model_name='microbiologia',
            name='informe_imagen',
            field=models.FileField(blank=True, null=True, upload_to='informes_legacy/'),
        ),
        migrations.AlterField(
            model_name='microbiologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
        migrations.AlterField(
            model_name='necropsia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
        migrations.AlterField(
            model_name='tubo',
            name='informe_imagen',
            field=models.FileField(blank=True, null=True, upload_to='informes_legacy/'),
        ),
        migrations.AlterField(
            model_name='tubo',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to='volantes/'),
        ),
    ]
