# Generated by Django 6.0.3 on 2026-03-11 16:24

import django.db.models.deletion
from django.db import migrations, models


def forwards_migrate_informe_target(apps, schema_editor):
    InformeResultado = apps.get_model('api', 'InformeResultado')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    model_labels = {
        'cassette_id': ('api', 'cassette'),
        'citologia_id': ('api', 'citologia'),
        'necropsia_id': ('api', 'necropsia'),
        'tubo_id': ('api', 'tubo'),
        'hematologia_id': ('api', 'hematologia'),
        'microbiologia_id': ('api', 'microbiologia'),
    }

    ct_map = {}
    for _, (app_label, model) in model_labels.items():
        ct, _ = ContentType.objects.get_or_create(app_label=app_label, model=model)
        ct_map[(app_label, model)] = ct.id

    for informe in InformeResultado.objects.all().iterator():
        target = None
        for fk_field, (app_label, model) in model_labels.items():
            fk_value = getattr(informe, fk_field, None)
            if fk_value:
                target = (ct_map[(app_label, model)], fk_value)
                break

        if target:
            informe.content_type_id = target[0]
            informe.object_id = target[1]
            informe.save(update_fields=['content_type', 'object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_seed_catalogoopcion'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeresultado',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='informeresultado',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_migrate_informe_target, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='informeresultado',
            name='cassette',
        ),
        migrations.RemoveField(
            model_name='informeresultado',
            name='citologia',
        ),
        migrations.RemoveField(
            model_name='informeresultado',
            name='hematologia',
        ),
        migrations.RemoveField(
            model_name='informeresultado',
            name='microbiologia',
        ),
        migrations.RemoveField(
            model_name='informeresultado',
            name='necropsia',
        ),
        migrations.RemoveField(
            model_name='informeresultado',
            name='tubo',
        ),
        migrations.AddIndex(
            model_name='informeresultado',
            index=models.Index(fields=['content_type', 'object_id'], name='informesres_content_6eb081_idx'),
        ),
    ]
