# Generated by Django 6.0.3 on 2026-03-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_cassette_informe_imagen_and_more'),
        ('api', '0022_limit_tipo_autopsia_to_clinica_medico_legal'),
    ]

    operations = [
    ]
