# Generated by Django 6.0.3 on 2026-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_rol_to_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='citologia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informacion_clinica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='informe_tincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='patologo_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='citologia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='id_citologia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='qr_citologia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='qr_imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
