# Generated by Django 6.0.3 on 2026-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_citologia_descripcion_microscopica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='necropsia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informacion_clinica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informe_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informe_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informe_imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informe_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='informe_tincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='patologo_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
