# Generated by Django 6.0.3 on 2026-03-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_necropsia_descripcion_microscopica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestracitologia',
            name='aproximacion_diagnostica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestracitologia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
