# Generated by Django 6.0.3 on 2026-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_set_analisis_informe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestranecropsia',
            name='prueba_complementaria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='prueba_complementaria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
