# Generated by Django 6.0.3 on 2026-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_repair_prueba_complementaria_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='descripcion_macroscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='numero_bloque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
