# Generated by Django 6.0.3 on 2026-03-20 14:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_bloque_macroscopica_to_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_qr),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
        migrations.AlterField(
            model_name='hematologia',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='hematologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='imagencitologia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='imagenhematologia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='imagenmicrobiologia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='imagennecropsia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='imagentubo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_imagen_muestra),
        ),
        migrations.AlterField(
            model_name='informeresultado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_resultado),
        ),
        migrations.AlterField(
            model_name='microbiologia',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='microbiologia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
        migrations.AlterField(
            model_name='necropsia',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='necropsia',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
        migrations.AlterField(
            model_name='tubo',
            name='informe_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_informe_imagen),
        ),
        migrations.AlterField(
            model_name='tubo',
            name='volante_peticion',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_volante),
        ),
    ]
