# Generated by Django 6.0.3 on 2026-03-20 14:45

import base64
import binascii
from uuid import uuid4

from django.core.files.base import ContentFile
from django.db import migrations


def _guess_extension(raw):
    header = raw[:16]
    if header.startswith(b"\xff\xd8\xff"):
        return ".jpg"
    if header.startswith(b"\x89PNG\r\n\x1a\n"):
        return ".png"
    if header.startswith((b"GIF87a", b"GIF89a")):
        return ".gif"
    if header.startswith(b"BM"):
        return ".bmp"
    if header.startswith(b"RIFF") and header[8:12] == b"WEBP":
        return ".webp"
    if header.startswith((b"II*\x00", b"MM\x00*")):
        return ".tiff"
    if header.startswith(b"%PDF"):
        return ".pdf"
    return ".bin"


def _to_raw_bytes(value):
    if value in (None, b"", ""):
        return None

    if isinstance(value, memoryview):
        return value.tobytes()

    if isinstance(value, bytearray):
        return bytes(value)

    if isinstance(value, bytes):
        return value

    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        if text.startswith("data:") and ";base64," in text:
            text = text.split(";base64,", 1)[1]
        try:
            decoded = base64.b64decode(text, validate=True)
            if decoded:
                return decoded
        except (binascii.Error, ValueError):
            return None

    return None


def _build_relative_name(model_name, field_name, ext):
    model_key = model_name.lower()

    if field_name == "volante_peticion":
        return f"volantes/{model_key}/{uuid4().hex}{ext}"

    if field_name == "informe_imagen":
        return f"informes/{model_key}/{uuid4().hex}{ext}"

    if field_name == "qr_imagen":
        return f"qr/{uuid4().hex}{ext}"

    if model_name == "InformeResultado" and field_name == "imagen":
        return f"informes_resultado/{uuid4().hex}{ext}"

    if field_name == "imagen":
        image_folder_map = {
            "Imagen": "cassettes",
            "ImagenCitologia": "citologias",
            "ImagenNecropsia": "necropsias",
            "ImagenTubo": "tubos",
            "ImagenHematologia": "hematologia",
            "ImagenMicrobiologia": "microbiologia",
        }
        folder = image_folder_map.get(model_name, "otros")
        return f"imagenes/{folder}/{uuid4().hex}{ext}"

    return f"migrados/{model_key}_{field_name}_{uuid4().hex}{ext}"


def migrate_binaries_to_files(apps, schema_editor):
    models_to_migrate = [
        ("api", "Cassette", ["volante_peticion", "informe_imagen"]),
        ("api", "Citologia", ["volante_peticion", "informe_imagen", "qr_imagen"]),
        ("api", "Necropsia", ["volante_peticion", "informe_imagen"]),
        ("api", "Tubo", ["volante_peticion", "informe_imagen"]),
        ("api", "Hematologia", ["volante_peticion", "informe_imagen"]),
        ("api", "Microbiologia", ["volante_peticion", "informe_imagen"]),
        ("api", "Imagen", ["imagen"]),
        ("api", "ImagenCitologia", ["imagen"]),
        ("api", "ImagenNecropsia", ["imagen"]),
        ("api", "ImagenTubo", ["imagen"]),
        ("api", "ImagenHematologia", ["imagen"]),
        ("api", "ImagenMicrobiologia", ["imagen"]),
        ("api", "InformeResultado", ["imagen"]),
    ]

    migrated = 0
    skipped = 0
    errors = 0

    for app_label, model_name, fields in models_to_migrate:
        Model = apps.get_model(app_label, model_name)

        for field_name in fields:
            for obj in Model.objects.all().iterator():
                value = getattr(obj, field_name, None)
                raw = _to_raw_bytes(value)
                if not raw:
                    skipped += 1
                    continue

                ext = _guess_extension(raw)
                relative_name = _build_relative_name(model_name, field_name, ext)

                try:
                    obj.__dict__[field_name] = ContentFile(raw, name=relative_name)
                    obj.save(update_fields=[field_name])
                    migrated += 1
                except Exception:
                    errors += 1
                    continue

    print(f"[0037] migrated={migrated} skipped={skipped} errors={errors}")


def reverse_migrate(apps, schema_editor):
    # Non-reversible migration: restoring binary blobs requires full DB backup.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_cassette_informe_imagen_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_binaries_to_files, reverse_migrate),
    ]
