# Generated by Django 6.0.3 on 2026-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_descripcion_microscopica_to_muestranecropsia'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrahematologia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestramicrobiologia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestratubo',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
